version: '3.8'

services:
  api:
    build: .
    command: python api/api.py
    ports:
      - "5000:5000"

  streamlit:
    build: .
    command: streamlit run api/streamlit.py
    ports:
      - "8501:8501"